# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJYOF-LDR6yXke0lX2BpYCa3m_7THEYO
"""

!pip install pypdf
!apt-get update
!apt-get install -y ghostscript

from pypdf import PdfReader, PdfWriter
import os, zipfile, subprocess
from google.colab import files

os.makedirs("output", exist_ok=True)

# ----------------------------
# Ghostscript compression
# ----------------------------
def compress_pdf(input_path, output_path, level="/ebook"):
    command = [
        "/usr/bin/gs",
        "-sDEVICE=pdfwrite",
        "-dCompatibilityLevel=1.4",
        f"-dPDFSETTINGS={level}",
        "-dNOPAUSE",
        "-dQUIET",
        "-dBATCH",
        f"-sOutputFile={output_path}",
        input_path
    ]
    subprocess.run(command, check=True)

# ----------------------------
# Parse page input
# ----------------------------
def process_input(text):
    return [p.strip() for p in text.split(',')]

# ============================
# MAIN LOOP (MULTI PDF SYSTEM)
# ============================
while True:

    print("\n📤 Upload one or more PDFs (you will process them one by one)")
    uploaded_files = files.upload()

    pdf_list = list(uploaded_files.keys())

    # Process each PDF separately
    for pdf_index, input_pdf in enumerate(pdf_list, start=1):

        print(f"\n==============================")
        print(f"📄 Processing PDF {pdf_index}: {input_pdf}")
        print(f"==============================")

        reader = PdfReader(input_pdf)
        total_pages = len(reader.pages)

        page_input = input("Enter pages (e.g., 1,2,5-10): ")
        parts = process_input(page_input)

        output_files = []

        for part in parts:
            writer = PdfWriter()

            if '-' in part:
                start, end = map(int, part.split('-'))
                for i in range(start-1, end):
                    if 0 <= i < total_pages:
                        writer.add_page(reader.pages[i])
                default_name = f"pages_{start}-{end}.pdf"
            else:
                page = int(part)
                if 1 <= page <= total_pages:
                    writer.add_page(reader.pages[page-1])
                default_name = f"page_{page}.pdf"

            custom_name = input(f"Filename for {default_name}: ").strip()

            if custom_name == "":
                custom_name = default_name
            elif not custom_name.lower().endswith(".pdf"):
                custom_name += ".pdf"

            path = os.path.join("output", custom_name)

            # Save PDF
            with open(path, "wb") as f:
                writer.write(f)

            # Compress
            compressed_path = path.replace(".pdf", "_compressed.pdf")
            compress_pdf(path, compressed_path, "/ebook")

            if os.path.getsize(compressed_path) > 2 * 1024 * 1024:
                print("⚠️ Over 2MB → stronger compression applied")
                compress_pdf(path, compressed_path, "/screen")

            size_mb = os.path.getsize(compressed_path) / (1024 * 1024)
            print(f"✅ Final size: {size_mb:.2f} MB")

            output_files.append(compressed_path)

        # ----------------------------
        # ZIP PER PDF (IMPORTANT)
        # ----------------------------
        zip_name = f"{os.path.splitext(input_pdf)[0]}_output.zip"

        with zipfile.ZipFile(zip_name, 'w') as zipf:
            for file in output_files:
                zipf.write(file, arcname=os.path.basename(file))

        print(f"\n📦 Downloading ZIP for {input_pdf} ...")
        files.download(zip_name)

    # ----------------------------
    # Ask if user wants more PDFs
    # ----------------------------
    again = input("\nDo you want to process more PDFs? (y/n): ").lower().strip()

    if again != "y":
        print("✅ All done!")
        break

!pip install pypdf
!apt-get update
!apt-get install -y ghostscript

from pypdf import PdfReader, PdfWriter
import os, zipfile, subprocess
from google.colab import files

os.makedirs("output", exist_ok=True)

# ----------------------------
# Ghostscript compression
# ----------------------------
def compress_pdf(input_path, output_path, level="/ebook"):
    command = [
        "/usr/bin/gs",
        "-sDEVICE=pdfwrite",
        "-dCompatibilityLevel=1.4",
        f"-dPDFSETTINGS={level}",
        "-dNOPAUSE",
        "-dQUIET",
        "-dBATCH",
        f"-sOutputFile={output_path}",
        input_path
    ]
    subprocess.run(command, check=True)

# ----------------------------
# Parse page input
# ----------------------------
def process_input(text):
    return [p.strip() for p in text.split(',')]

# ============================
# MAIN LOOP (MULTI PDF SYSTEM)
# ============================
while True:

    print("\n📤 Upload one or more PDFs (you will process them one by one)")
    uploaded_files = files.upload()

    pdf_list = list(uploaded_files.keys())

    # Process each PDF separately
    for pdf_index, input_pdf in enumerate(pdf_list, start=1):

        print(f"\n==============================")
        print(f"📄 Processing PDF {pdf_index}: {input_pdf}")
        print(f"==============================")

        reader = PdfReader(input_pdf)
        total_pages = len(reader.pages)

        page_input = input("Enter pages (e.g., 1,2,5-10): ")
        parts = process_input(page_input)

        output_files = []

        for part in parts:
            writer = PdfWriter()

            if '-' in part:
                start, end = map(int, part.split('-'))
                for i in range(start-1, end):
                    if 0 <= i < total_pages:
                        writer.add_page(reader.pages[i])
                default_name = f"pages_{start}-{end}.pdf"
            else:
                page = int(part)
                if 1 <= page <= total_pages:
                    writer.add_page(reader.pages[page-1])
                default_name = f"page_{page}.pdf"

            custom_name = input(f"Filename for {default_name}: ").strip()

            if custom_name == "":
                custom_name = default_name
            elif not custom_name.lower().endswith(".pdf"):
                custom_name += ".pdf"

            path = os.path.join("output", custom_name)

            # Save PDF
            with open(path, "wb") as f:
                writer.write(f)

            # Compress
            compressed_path = path.replace(".pdf", "_compressed.pdf")
            compress_pdf(path, compressed_path, "/ebook")

            if os.path.getsize(compressed_path) > 2 * 1024 * 1024:
                print("⚠️ Over 2MB → stronger compression applied")
                compress_pdf(path, compressed_path, "/screen")

            size_mb = os.path.getsize(compressed_path) / (1024 * 1024)
            print(f"✅ Final size: {size_mb:.2f} MB")

            output_files.append(compressed_path)

        # ----------------------------
        # ZIP PER PDF (IMPORTANT)
        # ----------------------------
        zip_name = f"{os.path.splitext(input_pdf)[0]}_output.zip"

        with zipfile.ZipFile(zip_name, 'w') as zipf:
            for file in output_files:
                zipf.write(file, arcname=os.path.basename(file))

        print(f"\n📦 Downloading ZIP for {input_pdf} ...")
        files.download(zip_name)

    # ----------------------------
    # Ask if user wants more PDFs
    # ----------------------------
    again = input("\nDo you want to process more PDFs? (y/n): ").lower().strip()

    if again != "y":
        print("✅ All done!")
        break